import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import requests
from dotenv import load_dotenv

load_dotenv()

# Configuration from environment variables
SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT")) if os.getenv("SMTP_PORT") else 587
SMTP_EMAIL = os.getenv("SMTP_EMAIL")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
FAST2SMS_API_KEY = os.getenv("FAST2SMS_API_KEY")


def send_email(receiver_email, subject, body):
    try:
        message = MIMEMultipart()
        message["From"] = SMTP_EMAIL
        message["To"] = receiver_email
        message["Subject"] = subject

        message.attach(MIMEText(body, "plain"))

        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT)
        server.starttls()
        server.login(SMTP_EMAIL, SMTP_PASSWORD)
        server.send_message(message)
        server.quit()

        return {
            "success": True,
            "message": "Email sent successfully."
        }
    except Exception as e:
        return {
            "success": False,
            "message": str(e)
        }


def send_sms(phone, message):
    # This prints the message to your Flask terminal window so you can see it working!
    print(f"\n[MOCK SMS GATEWAY] Sending text to {phone}...")
    print(f"Message content: {message}\n")
    
    # Return a simulated success response so your app routes think it succeeded
    return {
        "success": True,
        "message": "Mock SMS triggered successfully (Fast2SMS bypassed for free testing)."
    }

def create_email(receipt, items):
    body = f"""SmartPantry Expiry Reminder

Store
---------------------
{receipt.get('store_name', 'Unknown Store')}

Address
---------------------
{receipt.get('store_address', 'N/A')}

Purchase Date
---------------------
{receipt.get('purchase_date', 'N/A')}

Payment
---------------------
{receipt.get('payment_method', 'N/A')}

Total
---------------------
₹{receipt.get('receipt_total', '0.00')}

========================================
Products
"""

    for item in items:
        body += f"""
---------------------------------------
Name : {item.get('name', 'Item')}
Brand : {item.get('brand', 'Generic')}
Category : {item.get('category', 'Unknown')}
Price : ₹{item.get('price', 'N/A')}
Shelf Life : {item.get('estimated_shelf_life', 'N/A')}
Estimated Expiry : {item.get('estimated_expiry_start', 'N/A')} to {item.get('estimated_expiry_end', 'N/A')}
Storage : {item.get('storage', 'N/A')}
Nutrition : {item.get('nutrition_value', 'N/A')}
Risk : {item.get('risk_label', 'N/A')}
"""

    body += """
========================================
Please consume these items before expiry.

Generated by SmartPantry.
"""
    return body


def create_sms(receipt, items):
    # --- FIX: Streamlined text formatting for Fast2SMS Quick Route safety ---
    store = receipt.get('store_name', 'Pantry')
    text = f"SmartPantry: Expiry notice for items from {store}. Expiring soon: "
    
    item_summaries = []
    for item in items:
        item_summaries.append(f"{item.get('name')} ({item.get('estimated_expiry_end', 'N/A')})")
    
    text += ", ".join(item_summaries)
    text += ". Please check your SmartPantry dashboard app for complete details."
    return text